/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'email' : IDL.Text });
export const ChapterStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const Chapter = IDL.Record({
  'status' : ChapterStatus,
  'name' : IDL.Text,
  'subjectId' : IDL.Nat,
  'studyTimeMinutes' : IDL.Nat,
});
export const Time = IDL.Int;
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChapter' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addStudyTimeToChapter' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSubject' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChapterStats' : IDL.Func([], [IDL.Nat, IDL.Nat, IDL.Nat], ['query']),
  'getChaptersBySubject' : IDL.Func([IDL.Nat], [IDL.Vec(Chapter)], ['query']),
  'getDailyStudyGoal' : IDL.Func([], [IDL.Nat], ['query']),
  'getDashboardProgress' : IDL.Func([], [IDL.Nat], ['query']),
  'getSubjectProgress' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getTotalStudyTime' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDailyStudyGoal' : IDL.Func([IDL.Nat], [], []),
  'updateChapterStatus' : IDL.Func([IDL.Text, ChapterStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'email' : IDL.Text });
  const ChapterStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Chapter = IDL.Record({
    'status' : ChapterStatus,
    'name' : IDL.Text,
    'subjectId' : IDL.Nat,
    'studyTimeMinutes' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChapter' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addStudyTimeToChapter' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSubject' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChapterStats' : IDL.Func([], [IDL.Nat, IDL.Nat, IDL.Nat], ['query']),
    'getChaptersBySubject' : IDL.Func([IDL.Nat], [IDL.Vec(Chapter)], ['query']),
    'getDailyStudyGoal' : IDL.Func([], [IDL.Nat], ['query']),
    'getDashboardProgress' : IDL.Func([], [IDL.Nat], ['query']),
    'getSubjectProgress' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getTotalStudyTime' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDailyStudyGoal' : IDL.Func([IDL.Nat], [], []),
    'updateChapterStatus' : IDL.Func([IDL.Text, ChapterStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };